### ISSUE TITLE
Support for custom object ids

### ISSUE THREAD

**Issue by martinpfannemueller** [parse-community/Parse-SDK-Android#1087]
Using the allowCustomObjectId option of parse-server, it is possible to provide custom object ids on the client side. It seems to me, that there is no support for this yet in the Android SDK. I already tried to implement this by simply creating POST requests instead of a PUT in case allowCustomObjectId is true and an objectId is provided (see https://github.com/martinpfannemueller/Parse-SDK-Android). However, as I do not have the complete overview of the SDK, this currently does not really work yet.

Maybe there is somebody with more experience in developing the Android SDK who can provide this relatively simple feature more easily. In case I make progress, I will reference this issue in a possible pull request.

**Comment by cbaker6** [comment]
Though I haven’t used the Android SDK, I can tell from the code that the Android, IOS, and JS SDKs are designed the same. Because of this, the objectId in Android is probably never added to the encoded data sent to the parse server. I recommend looking at the JS PR I posted in response to your question I’m the iOS repo for guidance with fixing this here.

**Comment by L3K0V** [comment]
This was released with [2.1.0](https://github.com/parse-community/Parse-SDK-Android/blob/master/CHANGELOG.md#210-2021-11-21)
