### ISSUE TITLE
ParseObject implements Parcelable

### ISSUE THREAD

**Issue by WanClem** [parse-community/Parse-SDK-Android#122]
I think ParseObject needs to implement Serializable.In a scenario where a developer is building a long list of ParseObject items that are pulled from the internet and displayed on a list view,if serialized it could help mimick offline content on the occasion where the user has no connectivity.That is,the previously serialized list items could be deserialized and populated on the list view when there is no connectivity on the phone.I tried subclassing ParseObject to get this effect but the Problem is that Subclassing ParseObject is forcing me to use a Zero-Argument Constructor and a predefined className which leaves me with the question "What if I want to provide classNames dynamically without predefining with @ParseClassName annotation as done by ParseObject?." Please help.

**Comment by grantland** [comment]
First off, `Parcelable` is more efficient than `Serializable` for passing objects through `Intent`s, so use that when possible. I'll rename this issue as such.

Secondly, we're planning on converting `ParseObject` to implement `Serializable` at some point, but it's a bit more complicated that you might think:

1. Do we parcel just server data or server data and dirty changes?

    Right now we're planning on passing both server data and dirty changes. Once `object.revert()` lands in #112, you'll be able to clear dirty changes and have access the server data.

2. What do we do if there are multiple operation sets in the object's queue like we're in the middle of saving an object?

    The best option might be to consider the previous operations as failed and roll forward the changes into one operation set. This will mean that the unparceled object might have some dirty changes that will be persisted on the server and additional calls to `save()` will execute them again. Doing so will be fine for idempotent operations, but might cause some issues with `increment(key)` and `decrement(key)`. We can issue a logcat warning when parceling an object with in progress operations to alert them of these possible inconsistencies.

3. What do we do if the object has been deleted?

    This seems like a super rare case and might be fine doing nothing. The only side-affect of doing nothing will mean that the unparceled object will incorrectly return `false` from `isDirty()`.

4. What do we do if the object is currently being deleted?

    Follow (2) and assume the `delete()` has failed and warn in logcat. Same repercussions as (3).

5. What do we do for in progress `saveEventually()` or `deleteEventually()`?

    Follow (2) and assume the eventually calls failed and warn in logcat. Same repercussions as (2) as well.

6. Is it ok that the unparceled object will be the same instance when LDS is enabled?

    This seems fine and probably a better scenario since in progress calls to `save()`, `delete()`, `saveEventually()`, and `deleteEventually()` will notify the instance, although there's no way to subscribe to these changes. Will probably warn in logcat with in progress calls as well. If the process dies we'll get a new object instance with the operation set queue squashed, similar to (2) even if the operations complete since there's no way to update the originating `Intent`.

It'd also be great to hear developer's feedback on this since it'll be a huge change and has a lot of nuances so we can be sure we're going in the right direction with this feature.

**Comment by rustanacexd** [comment]
So a quick question. how do we pass a parse object if we cant implement serializable nor parcelable. assuming I don't want to convert into a pojo

**Comment by grantland** [comment]
If you want to use `ParseObject` data to inflate the UI in a new `Activity`, we recommend passing specific fields that you need for UI through the `Bundle` and inflating your UI with that data.

If you want to modify a `ParseObject` in a new `Activity`, we recommend passing the `className` and `objectId` through the `Bundle` and creating a pointer in the new `Activity` using `ParseObject.create(className, objectId)`.

**Comment by sbagadi** [comment]
I think the method is `createWithoutData(className, objectId)` because `ParseObject.create(className)` only takes one argument.

**Comment by grantland** [comment]
@sbagadi Oops, thanks! I've updated my comment.

**Comment by miav** [comment]
@grantland any updates on this?

**Comment by natario1** [comment]
Is there common agreement about the implementation of this feature? I’m not the right person to work on this, but I can trigger the easier steps for sure.

I believe the roadmap should be:
- Have `ParseGeoPoint` implement `Parcelable`. There is a open PR #619 
- Have `ParseFile` implement `Parcelable`. There was an attempt at #557 , but it has some issues. Namely it tries to parcel the whole byte[] array, which is not what we want. Parceling a dirty file should probably throw an exception. The other option is to save byte array to cache, but it’s not ideal to do IO stuff when parceling.
I have a working implementation and can PR if you wish.
- Somewhere along the road, bump min API level over 13 so we can use `ClassLoaderCreator` instead of `Creator`?
- Have `ParseACL` implement `Parcelable`.
- Have `ParseRelation` implement `Parcelable`.
- Have `ParseObject` implement `Parcelable`, following guidelines from @grantland from this post
- Have `ParseObject` subclasses parcel their own data and provide a creator
- Have `ParseQuery` implement `Parcelable`.

Each step has its nuances and considerations to be done, e.g. for `ParseObject` and `ParseQuery`, it is the untypedness of objects you can pass in (e.g. ParseObject.put and ParseQuery.equalTo). I think we can just throw if the object is not something we recognize. This is already happening in `ParseEncoder.encode(Object object)`.

GeoPoints and Files are easy, but in the long run we might start with a dedicated Encoder class that parcels unknown objects into a `Parcel` and throws if the object is not valid, just like ParseEncoder.

Given the complexity, these should be addressed as separate PRs (implementing Parcelable to just some of these does no harm anyway).

What do you think?
@rogerhu

**Comment by rogerhu** [comment]
Thanks for the write up.  I think the main issue raised in the questions raised about dirty/clean state and what to do about queued tasks.  There needs to be a warning about in-flight tasks

**Comment by natario1** [comment]
Personally I am fine with the idea of ignoring ongoing tasks, as grantland said. It should be very clear (with docs and log warnings) for developers that parceling objects with ongoing tasks is not safe.

Or, for 100% safety, we can throw if there are ongoing tasks. In this case we might add something like `boolean isParcelable()`, and `Task<Void> whenParcelable()` to ParseObject.

**Comment by natario1** [comment]
Looks to me that `ParseRelation` and `ParseACL` can’t be made Parcelable if `ParseObject` is not, because they hold references to objects.

So after files and geopoint I think we should start with `ParseObject` and its subclasses, and then add relations and ACLs.
