### ISSUE TITLE
Something wrong with snapshots?

### ISSUE THREAD

**Issue by natario1** [parse-community/Parse-SDK-Android#643]
Is there something wrong with snapshots?
I can’t find the latest versions in sonatype, last one is from two weeks ago, 1.14.2

https://oss.sonatype.org/content/repositories/snapshots/com/parse/parse-android/

**Comment by hermanliang** [comment]
Because of the organization was transferred from ParsePlatform to parse-community since 5th April.
Part of the repo url is not up to date. It should be fixed by PR #644.

**Comment by natario1** [comment]
I see, thanks @hermanliang !

**Comment by rogerhu** [comment]
Thanks.  Secondly plan is to move to Bintray and jFrog Oss.  Any concerns?

**Comment by flovilmart** [comment]
As long as it's properly advertised/documented. Can we plan for a transition period where both will be available? Add depreciation notices?

**Comment by Jawnnypoo** [comment]
Should be fine since the old versions will remain on maven Central and it will only affect people who are actively upgrading, so I don't think there is really a need for a transition phase

**Comment by flovilmart** [comment]
Alright then!

**Comment by flovilmart** [comment]
Is it possible to automate releases on tags like most of the other repos?

**Comment by Jawnnypoo** [comment]
It could potentially be done via some scripting on Travis. It is also done automatically with JitPack.io. Another plus for jitpack is that you do not need anything more than access to GitHub to do releases (don't need bintray or maven Central credentials).

**Comment by flovilmart** [comment]
So jitpack looks nice, seems that adding the custom maven repo isn't that bad, not an android user / dev so I don't really know if that's common / a source of problems potentially for users. What matters he most is the easy of use for users, even if we need to put some extra work to keep it up.

If we can keep things where they are published, I would not recommend changing :)

**Comment by Jawnnypoo** [comment]
Fair enough point, just thought I'd mention it as an option if we were looking to switch for whatever reasons. 👍

**Comment by flovilmart** [comment]
Eheh ;) still interesting to know such service exist, we should keep liveQuery and android SDK on the same distribution repos. Then, as long as we don't cause too much disruption, I'm fine with any.

I'll also create some parseplatform.org account for CI based builds so it's not personal account dépendant.

**Comment by rogerhu** [comment]
So here's my thought:

1) The plan is to move them all Android-related repos to use jCenter / jFrog OSS.
2) Most Android Studio users are already using jCenter anyways.
3) For repos which are still pointing to Maven Central, jCenter allows syncing to Maven central too.  The main issue is that Maven Central takes anywhere from 2-10 hours to sync whereas jCenter publishing is almost instantaneous. 
4) Sonatype is painful to release/distribute.  There are a lot of manual steps in approving a release and Bintray simplifies it.

**Comment by flovilmart** [comment]
I agree sonatype is a b****ch when it comes to releasing :)

**Comment by rogerhu** [comment]
I finally wrestled Bintray and Gradle down to the ground.

Starting with 1.15.3, all releases can be pushed through to Bintray, which means new versions will appear almost instantaneously instead of waiting hours for Maven to reindex.  

Once nice advantage is that Bintray signs the packages automatically and then pushes to Maven Central, automatically closing/releasing the snapshot too.  So no more manual intervention.

I'll be opening up pull requests in other Parse-related Android projects to do the same.

For now, snapshots will still be pushed to Sonatype.  That's lower priority to move over to jFrog OSS.

My ultimate goal is to expand the set of core volunteers who can help with releasing new versions.  It's a time-consuming process to write release notes, merge PRs, so this is the first step in getting the infra together so I'm not the only one doing it.
