### ISSUE TITLE
Document or fix proguard warnings

### ISSUE THREAD

**Issue by danepowell** [parse-community/Parse-SDK-Android#647]
On ParseSDK 1.15.1, if an app uses proguard with `minifyEnabled true` you must add this line to the app proguard rules to avoid errors when building the APK:
`-dontwarn okio.**`

What's odd is that the consumer proguard file provided by ParseSDK already includes this line, but it doesn't seem to have any effect. The parent application still must include it in its own proguard rules.

I suspect this is because the ParseSDK gradle file doesn't specify `minifyEnabled false`, though I'm not entirely sure.

ParseSDK should either fix its proguard/gradle files to avoid this error, or document that projects need to manually add this line (and also include it in the starter project template proguard file).

**Comment by rogerhu** [comment]
If you use `@aar`, does it change things?

```gradle
dependencies {
    compile 'com.parse:parse-android:1.15.2@aar'
}
```

**Comment by danepowell** [comment]
That used to make a difference, but not anymore since ParseSDK switched to aar packaging by default.

I still get proguard warnings if I include `@aar` and don't add `-dontwarn okio.**` to my own proguard rules.

**Comment by rogerhu** [comment]
minify should be not be used in the Parse SDK because otherwise ProGuard could easily optimize out functions that are publicly exposed but not necessarily used by the library itself.

I just realized 1.15.2 is missing the aar package (https://dl.bintray.com/parse/maven/com/parse/parse-android/1.15.2).  Will need to release to get this fixed.

**Comment by danepowell** [comment]
Parse SDK should not be minified, but it's okay for depending projects to be minified, correct? If so, how should gradle be set up to support this?

Right now the starter project just keeps minify completely disabled.

**Comment by rogerhu** [comment]
Yes the projects using the SDK should have them enabled.

The 1.15.1 release includes the AAR but I don't think the default packaging was changed to Aar until 1.15.2. 

I will need to rerelease and hopefully the proguard config will be picked up.

**Comment by rogerhu** [comment]
Please try with 1.15.3.  Only the AAR is being distributed (I'm open to people wanting the JAR) so it should use the Proguard file.

**Comment by danepowell** [comment]
Upgrading to 1.15.3 fixes the okio warnings, but now I get warnings about okhttp3.** (i.e. Warning:com.parse.ParseHttpClient$ParseOkHttpRequestBody: can't find superclass or interface okhttp3.RequestBody) and need to add this to my proguard file:
`-dontwarn okhttp3.**`

**Comment by Jawnnypoo** [comment]
Yep, this makes sense as it is part of the OkHttp ProGuard rules.
https://github.com/square/okhttp#proguard
 I'll go ahead and make a PR to add it in 👍

**Comment by hermanliang** [comment]
I think it's due to the dependencies (bolt and OkHttp) are not included in the pom file.
https://jcenter.bintray.com/com/parse/parse-android/1.15.3/:parse-android-1.15.3.pom

You may use
```groovy
dependencies {
  compile 'com.parse:parse-android:1.15.3'
  compile 'com.parse.bolts:bolts-tasks:1.4.0'
  compile 'com.squareup.okhttp3:okhttp:3.6.0'
}
```

before the dependency problem is being fixed.

**Comment by Jawnnypoo** [comment]
Yeah, it is more than likely something like that. If I run the starter project now with the current ProGuard rules, with ProGuard enabled, it seems to build just fine. @hermanliang Is there an easy way we can add those to the pom file so that they are pulled in?

**Comment by hermanliang** [comment]
I follow this example configuration in my own project and dependencies can be included in the pom file.
https://github.com/bintray/bintray-examples/blob/master/gradle-bintray-plugin-examples/android-maven-example/build.gradle

Configuration of parse-android is more like this example
https://github.com/bintray/bintray-examples/blob/master/gradle-bintray-plugin-examples/publications-example/build.gradle

I'm not familiar with bintray, but maybe we can try to follow the first example to configure the bintray.

**Comment by rogerhu** [comment]
Thanks for spotting the issue with the dependencies @hermanliang . I had to add https://github.com/parse-community/Parse-SDK-Android/commit/b15f25512e37f58aabc922f9383860c2e7b14496 to include the dependencies.

1.15.4 has been pushed to jCenter and now is being synced to Maven Central.  Try again?

**Comment by rogerhu** [comment]
Just a footnote about your question re: https://github.com/bintray/bintray-examples/blob/master/gradle-bintray-plugin-examples/android-maven-example/build.gradle#L104.

The 1st approach you proposed was the 1st and easiest approach to try.  The issue I ran into is that it uploads to the wrong location because the artifact is `parse-android` but the library is currently stored in Parse/.  As a result, the Bintray plugin uploads the files to the wrong location.  Believe, I spent many hours before realizing the upload location is determined by the `Parse` name  (https://github.com/bintray/gradle-bintray-plugin/blob/master/src/main/groovy/com/jfrog/bintray/gradle/Artifact.groovy#L15-L18).

So my 2nd approach was to use the maven-publish, which lets you override the artifact name.  The challenge is that even after many years, using the maven-publish plugin has lots of problems, namely it doesn't provide GPG signing and it doesn't include dependencies by default.   I got around the 1st issue by letting Bintray handle it automatically.  The 2nd issue required that change.

I think I might just rename the `Parse` dir to `parse-android` and then I can revert back to the 1st approach.  Thoughts?

**Comment by hermanliang** [comment]
Gotcha! The first approach is more simple but it uses the project name as the artifact name.
If using first approach, you my not need to rename the `Parse` dir, just configure `settings.gradle` file like this.

```
include ':Parse'
include ':ParseStarterProject'
project(':Parse').name = 'parse-android'
```

**Comment by rogerhu** [comment]
Good call.  Changed here: https://github.com/parse-community/Parse-SDK-Android/commit/5b4b16b2d869d9f00929deb335cc92148f40b4ad

**Comment by rogerhu** [comment]
Never mind, the configuration archives doesn't generate a suitable POM file for Maven Central (http://central.sonatype.org/pages/requirements.html).  I'd still have a custom maven-plugin job to generate that one.  Reverted this commit to the original one and everything works fine.

**Comment by danepowell** [comment]
1.15.5 compiles cleanly and solves the original issue for me, thanks!
