### ISSUE TITLE
Android FireBase Push Setup?

### ISSUE THREAD

**Issue by gateway** [parse-community/Parse-SDK-Android#786]
Hi, we are in the process of building the android version of our iOS app.  However we have come along a stumbling block on the proper method of setup to get push working with Android.  As we all know Google has phased out the GCM system in favor for Firebase, and those of you luckily enough to have had GCM prior can easily upgrade, but those that have not are at a loss of a way to properly  get push enabled.

Here is what I know so far.
You need to set up a Firebase account https://console.firebase.google.com and create a project.  This allows you to get a google-service.json file which is required along with your Legacy Server Key and Sender ID (found in the settings section under Cloud Messaging.)

You need to do X in your https://console.developers.google.com .. this is where Im sorta at a loss.  Some loose documentation on create a project, enable fire api, create some keys etc.. 

Of course their is a bunch of stuff you also need to add to your Android Manifest file.

So anyone have a newer walk though or could outline a step by step?

Sorry this is not a code issue but a documentation issue :)

**Comment by Jawnnypoo** [comment]
Hey there, Parse does not support FCM yet. There are issues out there, but it is not resolved yet. For now, once you have created the Firebase project, you need to go to Project Settings -> Cloud Messaging -> Legacy server key, like you mentioned. You put these in your push config on your server. The Android guide setup can be found here: http://docs.parseplatform.org/android/guide/#push-notifications. Here is an example of a server configured:
https://glitch.com/edit/#!/test-parse-server

Everything else you need in the Android app should be outlined in the guide. Closing since its not really an issue, feel free to use Stack Overflow in the future for questions like this as they will get more attention and have more reach 😄

**Comment by rogerhu** [comment]
@natario1 I know you were working on FCM...how challenging is it to add?

**Comment by rogerhu** [comment]
Take a look at: https://github.com/codepath/android_guides/wiki/Push-Notifications-Setup-for-Parse

**Comment by natario1** [comment]
We have an interface to be implemented, and google provides the FCM library which I would use here, so it's just wrapping the two together.

AFAIR I put this aside because the parse-server adapter needed some changes for this to work out, due to limitations in the FCM library for Android (like, a specific flag in the payload was needed).

When this is done, the only tricky thing is to update gracefully the installations to receive the new kind of push.

**Comment by flovilmart** [comment]
We should probably update the documentation for the setup with legacy key, as it’a still technically working with parse-server and FCM is confusing everyone right?
