### ISSUE TITLE
Android API documentation links to wrong package

### ISSUE THREAD

**Issue by aekoch** [parse-community/Parse-SDK-Android#834]
The link on parseplatform.org to the android sdk documentation does not point to the correct package. Instead it points to the com.parse.gcm package.  All links I have been able to find to the api reference lead to this same place.

http://parseplatform.org/Parse-SDK-Android/api/

Apologies if this is not the correct place to report this.

**Comment by addisonElliott** [comment]
@aekoch I've noticed this issue too. I think it has to do with the major code changes that were done for GCM.

Before that, the API reference docs were working well I believe.

Let me know if you find the issue. If I find time, I'll try to hunt it down as well.

**Comment by flovilmart** [comment]
@jhansche @rogerhu it seems that the whole documentation gets overridden as we publish 2 packages now (instead of 1).

Is it possible that the command [`./gradlew javadocRelease`](https://github.com/parse-community/Parse-SDK-Android/blob/master/.travis.yml#L30) produces the 2 sets of documentation consecutively so only the last generated one is there in docs?

**Comment by rogerhu** [comment]
We need to add javadocrelease to the build step again.. I removed
temporarily to get the fcm stuff out

**Comment by flovilmart** [comment]
@rogerhu, the whole doc is back:

http://parseplatform.org/Parse-SDK-Android/api/

And fcm and gcm are on the sub paths:

http://parseplatform.org/Parse-SDK-Android/api/fcm/

http://parseplatform.org/Parse-SDK-Android/api/gcm/
