### ISSUE TITLE
Parse SDK JVM

### ISSUE THREAD

**Issue by flovilmart** [parse-community/Parse-SDK-Android#864]
(originally posted here #728 by @holgerbrandl

It would be great if the API could be also used to build JVM applications (targeting the desktop/server rather than the mobile).

I guess the public API would look pretty similar but the backend would need to be decoupled from android to provide an alternative JVM backend.

Or is there a different parse SDK for the JVM? I've seen the generic REST API but it lacks some convenience compared to the nice way the Android SDK works.

**Comment by flovilmart** [comment]
Is Bolts android dependant? I wasn’t sure. Keeping a good asynchronous library is crutial inside, to minimize the risks of errors while refactoring. Java isn’t fun on the point of object extensions :/

**Comment by Jawnnypoo** [comment]
Bolts is indeed dependent on the Android framwork. We could potentially model off of something like Retrofit, where the return type can be made dynamic and can support different async methods. Bolts is also the source of quite a few bugs and confusion when dealing with this framework I think. If the SDK were to be written again, I am sure Rx would be a first class citizen over Bolts. But since all synchronous calls from the SDK are actually just async bolts calls with waiting attached to them, the synchronous calls end up with a lot of the same bug and problems. As for the risk of errors while refactoring, I would say it will be hard to avoid a pretty huge refactor, if the end goal is to support the JVM with all the same current features.

**Comment by flovilmart** [comment]
Yeah, sure. This is something i’ve Been thinking about a lot for objective c as well. But given that Bolts was born out of the Parse SDK’s originally, extracting it out is really making a heart and lung transplant

**Comment by holgerbrandl** [comment]
For sure refactoring the android client seems the most obvious choice. Clearly internals such as Bolts may render such an idea impractical. However, other runtime clients such as https://github.com/parse-community/Parse-SDK-dotNET seem possible as well, so I still don't quite understand why a jvm client would be so hard to implement?
