### ISSUE TITLE
What is the reason for killing git history for the project?

### ISSUE THREAD

**Issue by vovkab** [parse-community/Parse-SDK-Android#884]
Changes that have been made in 

https://github.com/parse-community/Parse-SDK-Android/pull/855
https://github.com/parse-community/Parse-SDK-Android/pull/861

Deleted all git history. As I can see almost all files lost their history.

Why?

**Comment by addisonElliott** [comment]
Not entirely sure I understand what you mean. Looking on Github, there still seems to be history before these commits (I haven't checked locally if that is the case).

Can you elaborate please?

**Comment by Jawnnypoo** [comment]
Are you referring to the fact that reformatting and changing the directory name changed the git blame to all point to those commits?

Yes, that is an unfortunate side effect of performing those actions, but you can always go to a tag or navigate the git history manually to figure out the changes.

**Comment by vovkab** [comment]
That is not a side effect, git support moving/renaming files with preserving file history. You just need to do it properly to make sure you don't loos it all.

**Comment by flovilmart** [comment]
@vovkab next time you should probably take the responsibility of doing it instead of complaining that other people maintain the project so you can enjoy it. Also, this language goes against our community guidelines. Please consider this the last warning.

**Comment by flovilmart** [comment]
> Though I don't think it is fair to other contributors that all their history is gone now.

The change happend on the 23rd of July, while I appreciate your 'concern' about other 'contributors' history, you are neither a contributor at this time, never opened an issue nor got a pull request merged on this project.

The fact that you were potentially running a fork and then were hurt by one of our refactoring is on **you**, not on us. If you wish to avoid such things in the future, you know exactly what to do.

> I can help to make this history right if you think we could reset some of the history that was broken and just rewind it?

At this time, I'm not sure this is worth for you to get through that trouble. I believe @Jawnnypoo did to the best of his knowledge just renamed the `Parse` folder into `parse` and that git itself screwed up and saw it as a delete / add. As you can probably notice in the PR #855 and the individual commits:

https://github.com/parse-community/Parse-SDK-Android/pull/855/commits/0247ff3060005d2b0f200bab0abf44a8858db4f7

https://github.com/parse-community/Parse-SDK-Android/pull/855/commits/47922481b5a1b94d76596c780485acc2d1d86823

All are proper files move.

Then perhaps when merging, this should have been merged instead of squashed, and perhaps this is where git lost it's mind, who knows. But AFAIU, I can't blame @Jawnnypoo as you're so eager and easy to do.

Moving forward, I expect a better behaviour from you @vovkab, given you have no seniority nor experience with this project, nor you are a maintainer. Having been a maintainer/contributor/watcher of this project and engaged you could have easily prevented the merge to happen.

In the end, you can always access the original history of the file before the move with:

```
git log Parse/src/main/java/com/parse/ParseObject.java
```

**Comment by vovkab** [comment]
> I appreciate your 'concern' about other 'contributors' history, you are neither a contributor at this time, never opened an issue nor got a pull request merged on this project.

I was trying to fix an issue with StackOverflow in the source code and submit a PR, that is why I actually noticed that all history was gone. While it is possible to go back and forth and try to compare files in different commits/branches and try to make sense of them, understand how breaking change was introduced, what was pull requests id's, read description of the change and etc, it is now really a pain to do.

> 'concern' about other 'contributors'

Not sure what using quotes should mean exactly?

> The fact that you were potentially running a fork and then were hurt by one of our refactoring is on you, not on us. If you wish to avoid such things in the future, you know exactly what to do.

Nope, I'm not doing a fork. Imo repo maintainers should have cought this though, but `¯\_(ツ)_/¯`

> Then perhaps when merging, this should have been merged instead of squashed, and perhaps this is where git lost it's mind, who knows.

Exactly. You are not supposed to move and change files in the same commit. If project is using squash strategy (project settings) this means you should not be doing multiple things in the same PR, but `¯\_(ツ)_/¯`

## How to fix it

As I can we lost all history in cedc1dfb03348761688d5abd87c552a1b9cd4b19. And the reason is because we did reformatting **and** moved files **and** then squashed everything. So the fix would be to un saquash it. 

Here is step by step instruction:

1. Checkout branch we want to fix
`$ git checkout master`

2. Start rebase before broken commit
`$ git rebase -i cedc1df~2`

3. Stop for editing before broken commit:
`e b0b00d1 Save eventually issue (#831)`

4. Pull in original changes from PR before squash:
`$ git pull origin refs/pull/855/head`

5. Skip next commit, since it will be empty:
`$ git rebase --skip`

6. Sync your tags. There are 5 tags, they need to be synced manually. Just move them to the same commits, should be easy to do.

7. Push your changes to origin. Since we have changed history we would need to do force push:
`$ git push -f`

Just for the comparison:

### History before:
```
$ git log --follow --oneline parse/src/main/java/com/parse/ParseObject.java
0cfc67e Cleanup (#861)
c2103e1 (tag: 1.18.0) Nullability annotations (#857)
cedc1df Formatting (#855)
```

### History after doing a "fix"

```
$ git log --follow --oneline parse/src/main/java/com/parse/ParseObject.java
9753f9c Cleanup (#861)
c042756 Nullability annotations (#857)
901a972 Remove references to library version, since they would no longer be accurate
03ebc2f Auto formatting of all files using default Android Studio lint rules
4792248 Rename part 2
0247ff3 Rename part 1
41c7979 Make things public for Parse LiveQuery
b0b00d1 Save eventually issue (#831)
8b6c1c1 Delete issue (#832)
ff3e27b Annotate nullable methods on ParseObject
e86b920 Remove package comments (#824)
a848b04 feat: Make ParseObject availableKeys Set a thread safe synchronizedSet (#795)
937fc85 Allow setting of max retries (#782)
351d54b Add Type Polygon to Schema and PolygonContains to query (#696)
1983eee Bump to 1.15.4-SNAPSHOT
7821ea3 (tag: 1.15.3) Bump to 1.15.3
...
```

I hope this help.

p.s. pushed my experiment branch here:
https://github.com/vovkab/Parse-SDK-Android/tree/fix-master

**Comment by flovilmart** [comment]
Thanks a thousand times for your condescending tone but we won’t rewrite the history of the master branch at that time.
